version: '2'
services:
  ide:
    image: sway
#    image: psharkey/netbeans-8.1:latest
    environment:
      - DISPLAY=novnc:0.0
      - XDG_RUNTIME_DIR=/home/Rohan
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY 
      - WLR_BACKENDS=headless
      - WLR_LIBINPUT_NO_DEVICES=1 
    command: dbus-run-session -- sway
    user: Rohan
    tty: true
    stdin_open: true
    volumes:
      -  $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/home/Rohan/$WAYLAND_DISPLAY 
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
    image: psharkey/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    ports:
      - "8081:8080"
    networks:
      - x11
networks:
  x11:
